import type { InsuranceLine, InsuranceLineAlias } from "../entities/canonical";

export const insuranceLinesCatalog: InsuranceLine[] = [
  { lineId: "accidentes-y-enfermedades", canonicalName: "ACCIDENTES Y ENFERMEDADES", displayName: "Accidentes y Enfermedades", parentLineId: null, sortOrder: 10 },
  { lineId: "accidentes-escolares", canonicalName: "ACCIDENTES ESCOLARES", displayName: "Accidentes Escolares", parentLineId: "accidentes-y-enfermedades", sortOrder: 11 },
  { lineId: "accidentes-personales", canonicalName: "ACCIDENTES PERSONALES", displayName: "Accidentes Personales", parentLineId: "accidentes-y-enfermedades", sortOrder: 12 },
  { lineId: "salud-y-hospitalizacion", canonicalName: "SALUD Y HOSPITALIZACIÓN", displayName: "Salud y Hospitalización", parentLineId: "accidentes-y-enfermedades", sortOrder: 13 },
  { lineId: "fianzas", canonicalName: "FIANZAS", displayName: "Fianzas", parentLineId: null, sortOrder: 20 },
  { lineId: "fidelidad", canonicalName: "FIDELIDAD", displayName: "Fidelidad", parentLineId: "fianzas", sortOrder: 21 },
  { lineId: "garantia", canonicalName: "GARANTÍA", displayName: "Garantía", parentLineId: "fianzas", sortOrder: 22 },
  { lineId: "otras-fianzas", canonicalName: "OTRAS FIANZAS", displayName: "Otras Fianzas", parentLineId: "fianzas", sortOrder: 23 },
  { lineId: "otros-seguros-generales", canonicalName: "OTROS SEGUROS GENERALES", displayName: "Otros Seguros Generales", parentLineId: null, sortOrder: 30 },
  { lineId: "agricola", canonicalName: "AGRÍCOLA", displayName: "Agrícola", parentLineId: "otros-seguros-generales", sortOrder: 31 },
  { lineId: "aviacion", canonicalName: "AVIACIÓN", displayName: "Aviación", parentLineId: "otros-seguros-generales", sortOrder: 32 },
  { lineId: "banqueros", canonicalName: "BANQUEROS", displayName: "Banqueros", parentLineId: "otros-seguros-generales", sortOrder: 33 },
  { lineId: "calderas", canonicalName: "CALDERAS", displayName: "Calderas", parentLineId: "otros-seguros-generales", sortOrder: 34 },
  { lineId: "casco-maritimo", canonicalName: "CASCO MARÍTIMO", displayName: "Casco Marítimo", parentLineId: "otros-seguros-generales", sortOrder: 35 },
  { lineId: "dinero-y-valores", canonicalName: "DINERO Y VALORES", displayName: "Dinero y Valores", parentLineId: "otros-seguros-generales", sortOrder: 36 },
  { lineId: "equipo-de-contratistas", canonicalName: "EQUIPO DE CONTRATISTAS", displayName: "Equipo de Contratistas", parentLineId: "otros-seguros-generales", sortOrder: 37 },
  { lineId: "equipo-electronico", canonicalName: "EQUIPO ELECTRÓNICO", displayName: "Equipo Electrónico", parentLineId: "otros-seguros-generales", sortOrder: 38 },
  { lineId: "montaje", canonicalName: "MONTAJE", displayName: "Montaje", parentLineId: "otros-seguros-generales", sortOrder: 39 },
  { lineId: "otros-ramos", canonicalName: "OTROS RAMOS", displayName: "Otros Ramos", parentLineId: "otros-seguros-generales", sortOrder: 40 },
  { lineId: "responsabilidad-civil", canonicalName: "RESPONSABILIDAD CIVIL", displayName: "Responsabilidad Civil", parentLineId: "otros-seguros-generales", sortOrder: 41 },
  { lineId: "riesgos-profesionales", canonicalName: "RIESGOS PROFESIONALES", displayName: "Riesgos Profesionales", parentLineId: "otros-seguros-generales", sortOrder: 42 },
  { lineId: "robo-y-hurto", canonicalName: "ROBO Y HURTO", displayName: "Robo y Hurto", parentLineId: "otros-seguros-generales", sortOrder: 43 },
  { lineId: "rotura-de-cristales", canonicalName: "ROTURA DE CRISTALES", displayName: "Rotura de Cristales", parentLineId: "otros-seguros-generales", sortOrder: 44 },
  { lineId: "rotura-de-maquinaria", canonicalName: "ROTURA DE MAQUINARIA", displayName: "Rotura de Maquinaria", parentLineId: "otros-seguros-generales", sortOrder: 45 },
  { lineId: "transporte-aereo", canonicalName: "TRANSPORTE AÉREO", displayName: "Transporte Aéreo", parentLineId: "otros-seguros-generales", sortOrder: 46 },
  { lineId: "transporte-maritimo", canonicalName: "TRANSPORTE MARÍTIMO", displayName: "Transporte Marítimo", parentLineId: "otros-seguros-generales", sortOrder: 47 },
  { lineId: "transporte-terrestre", canonicalName: "TRANSPORTE TERRESTRE", displayName: "Transporte Terrestre", parentLineId: "otros-seguros-generales", sortOrder: 48 },
  { lineId: "seguro-de-vida", canonicalName: "SEGURO DE VIDA", displayName: "Seguro de Vida", parentLineId: null, sortOrder: 50 },
  { lineId: "seguro-de-sepelio", canonicalName: "SEGURO DE SEPELIO", displayName: "Seguro de Sepelio", parentLineId: "seguro-de-vida", sortOrder: 51 },
  { lineId: "vida-colectivo", canonicalName: "VIDA COLECTIVO", displayName: "Vida Colectivo", parentLineId: "seguro-de-vida", sortOrder: 52 },
  { lineId: "vida-individual", canonicalName: "VIDA INDIVIDUAL", displayName: "Vida Individual", parentLineId: "seguro-de-vida", sortOrder: 53 },
  { lineId: "seguros-generales", canonicalName: "SEGUROS GENERALES", displayName: "Seguros Generales", parentLineId: null, sortOrder: 60 },
  { lineId: "incendio-y-lineas-aliadas", canonicalName: "INCENDIO Y LÍNEAS ALIADAS", displayName: "Incendio y Líneas Aliadas", parentLineId: "seguros-generales", sortOrder: 61 },
  { lineId: "vehiculos-automotores", canonicalName: "VEHÍCULOS AUTOMOTORES", displayName: "Vehículos Automotores", parentLineId: "seguros-generales", sortOrder: 62 }
];

export const insuranceLineAliases: InsuranceLineAlias[] = [
  { alias: "ACCIDENTES Y ENFERMADADES", lineId: "accidentes-y-enfermedades", source: "dictionary" },
  { alias: "ACCIDENTES Y ENFERMEDADES", lineId: "accidentes-y-enfermedades", source: "dictionary" },
  { alias: "ACCIDENTES Y ENFERMADEDES", lineId: "accidentes-y-enfermedades", source: "dictionary" },
  { alias: "SALUD Y HOSPITAL", lineId: "salud-y-hospitalizacion", source: "dictionary" },
  { alias: "SALUD Y HOSPITALIZACION", lineId: "salud-y-hospitalizacion", source: "dictionary" },
  { alias: "OTROS SEGUROS GENERALES", lineId: "otros-seguros-generales", source: "dictionary" },
  { alias: "INCENDIO Y LINEA ALIADAS", lineId: "incendio-y-lineas-aliadas", source: "dictionary" },
  { alias: "INCENDIO Y LÍNEA ALIADAS", lineId: "incendio-y-lineas-aliadas", source: "dictionary" },
  { alias: "INCENDIO Y LINEAS ALIADAS", lineId: "incendio-y-lineas-aliadas", source: "dictionary" },
  { alias: "CASCO MARITÍMO", lineId: "casco-maritimo", source: "dictionary" },
  { alias: "VEHICULOS AUTOMOTORES", lineId: "vehiculos-automotores", source: "dictionary" },
  { alias: "VEHÍCULOS AUTOMOTORES", lineId: "vehiculos-automotores", source: "dictionary" },
  { alias: "OTRAS FINANZAS", lineId: "otras-fianzas", source: "dictionary" },
  { alias: "OTRAS FIANZAS", lineId: "otras-fianzas", source: "dictionary" },
  { alias: "GARANTIA", lineId: "garantia", source: "dictionary" },
  { alias: "AVIACION", lineId: "aviacion", source: "dictionary" },
  { alias: "AGRICOLA", lineId: "agricola", source: "dictionary" },
  { alias: "TRANSPORTE AEREO", lineId: "transporte-aereo", source: "dictionary" },
  { alias: "TRANSPORTE MARITIMO", lineId: "transporte-maritimo", source: "dictionary" },
  { alias: "SEGURO DE VIDA", lineId: "seguro-de-vida", source: "dictionary" }
];
